-- Parent-teacher controlled messaging.
-- Text-only first phase.

create table if not exists public.parent_teacher_messages (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  parent_id uuid references public.profiles(id) on delete set null,
  teacher_id uuid references public.profiles(id) on delete set null,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) > 0 and char_length(body) <= 2000),
  parent_read_at timestamptz,
  teacher_read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists parent_teacher_messages_student_created_idx
on public.parent_teacher_messages(student_id, created_at);

create index if not exists parent_teacher_messages_sender_idx
on public.parent_teacher_messages(sender_id, created_at desc);

alter table public.parent_teacher_messages enable row level security;

drop policy if exists parent_teacher_messages_select on public.parent_teacher_messages;
create policy parent_teacher_messages_select
on public.parent_teacher_messages
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
  or exists (
    select 1
    from public.parent_student ps
    where ps.parent_id = auth.uid()
      and ps.student_id = parent_teacher_messages.student_id
  )
  or exists (
    select 1
    from public.students s
    join public.teacher_class tc on tc.class_id = s.class_id
    where s.id = parent_teacher_messages.student_id
      and tc.teacher_id = auth.uid()
  )
);

drop policy if exists parent_teacher_messages_insert on public.parent_teacher_messages;
create policy parent_teacher_messages_insert
on public.parent_teacher_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
    or exists (
      select 1
      from public.parent_student ps
      where ps.parent_id = auth.uid()
        and ps.student_id = parent_teacher_messages.student_id
    )
    or exists (
      select 1
      from public.students s
      join public.teacher_class tc on tc.class_id = s.class_id
      where s.id = parent_teacher_messages.student_id
        and tc.teacher_id = auth.uid()
    )
  )
);

drop policy if exists parent_teacher_messages_update_read on public.parent_teacher_messages;
create policy parent_teacher_messages_update_read
on public.parent_teacher_messages
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
  or exists (
    select 1
    from public.parent_student ps
    where ps.parent_id = auth.uid()
      and ps.student_id = parent_teacher_messages.student_id
  )
  or exists (
    select 1
    from public.students s
    join public.teacher_class tc on tc.class_id = s.class_id
    where s.id = parent_teacher_messages.student_id
      and tc.teacher_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
  or exists (
    select 1
    from public.parent_student ps
    where ps.parent_id = auth.uid()
      and ps.student_id = parent_teacher_messages.student_id
  )
  or exists (
    select 1
    from public.students s
    join public.teacher_class tc on tc.class_id = s.class_id
    where s.id = parent_teacher_messages.student_id
      and tc.teacher_id = auth.uid()
  )
);

create or replace function public.protect_parent_teacher_message_updates()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  is_admin boolean;
  can_mark_parent boolean;
  can_mark_teacher boolean;
begin
  if new.id <> old.id
    or new.student_id <> old.student_id
    or new.parent_id is distinct from old.parent_id
    or new.teacher_id is distinct from old.teacher_id
    or new.sender_id <> old.sender_id
    or new.body <> old.body
    or new.created_at <> old.created_at then
    raise exception 'only read status can be updated';
  end if;

  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  ) into is_admin;

  select exists (
    select 1 from public.parent_student ps
    where ps.parent_id = auth.uid()
      and ps.student_id = old.student_id
  ) into can_mark_parent;

  select exists (
    select 1
    from public.students s
    join public.teacher_class tc on tc.class_id = s.class_id
    where s.id = old.student_id
      and tc.teacher_id = auth.uid()
  ) into can_mark_teacher;

  if new.parent_read_at is distinct from old.parent_read_at
    and not (is_admin or can_mark_parent) then
    raise exception 'not allowed to update parent read status';
  end if;

  if new.teacher_read_at is distinct from old.teacher_read_at
    and not (is_admin or can_mark_teacher) then
    raise exception 'not allowed to update teacher read status';
  end if;

  return new;
end;
$$;

drop trigger if exists protect_parent_teacher_message_updates_trigger on public.parent_teacher_messages;
create trigger protect_parent_teacher_message_updates_trigger
before update on public.parent_teacher_messages
for each row execute function public.protect_parent_teacher_message_updates();

grant select, insert, update on public.parent_teacher_messages to authenticated;
grant usage, select on sequence public.parent_teacher_messages_id_seq to authenticated;
