-- Tuition system phase 1
-- Run this file once in Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.fee_terms (
  id bigint generated by default as identity primary key,
  academic_year text not null,
  term_no smallint not null check (term_no in (1, 2, 3)),
  name text not null,
  due_date date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (academic_year, term_no)
);

create table if not exists public.fee_items (
  id bigint generated by default as identity primary key,
  term_id bigint not null references public.fee_terms(id) on delete cascade,
  name text not null,
  default_amount numeric(12,2) not null default 0 check (default_amount >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.student_invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_no text not null unique,
  student_id bigint not null references public.students(id) on delete cascade,
  term_id bigint not null references public.fee_terms(id),
  due_date date,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  paid_amount numeric(12,2) not null default 0 check (paid_amount >= 0),
  status text not null default 'unpaid'
    check (status in ('draft','unpaid','pending','paid','cancelled')),
  notes text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, term_id)
);

create table if not exists public.invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id uuid not null references public.student_invoices(id) on delete cascade,
  fee_item_id bigint references public.fee_items(id),
  description text not null,
  amount numeric(12,2) not null check (amount >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.student_invoices(id) on delete cascade,
  parent_id uuid not null default auth.uid() references public.profiles(id),
  amount numeric(12,2) not null check (amount > 0),
  method text not null default 'bank_transfer'
    check (method in ('bank_transfer','cash','promptpay')),
  paid_at timestamptz not null default now(),
  slip_path text,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected','cancelled')),
  review_note text,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.receipts (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null unique references public.payments(id) on delete restrict,
  receipt_no text not null unique,
  issued_at timestamptz not null default now(),
  issued_by uuid references public.profiles(id)
);

create sequence if not exists public.receipt_number_seq;

create or replace function public.is_finance_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('finance', 'admin')
  );
$$;

create or replace function public.can_access_student(target_student_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_finance_staff()
    or exists (
      select 1 from public.students s
      where s.id = target_student_id and s.profile_id = auth.uid()
    )
    or exists (
      select 1 from public.parent_student ps
      where ps.student_id = target_student_id and ps.parent_id = auth.uid()
    );
$$;

create or replace function public.create_fee_invoices(
  p_term_id bigint,
  p_description text,
  p_amount numeric,
  p_due_date date,
  p_class_id bigint default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare created_count integer := 0;
begin
  if not public.is_finance_staff() then
    raise exception 'Finance staff permission required';
  end if;
  if p_amount <= 0 or nullif(trim(p_description), '') is null then
    raise exception 'Description and positive amount are required';
  end if;

  with inserted as (
    insert into public.student_invoices (
      invoice_no, student_id, term_id, due_date, status, created_by
    )
    select
      'INV-' || replace(t.academic_year, ' ', '') || '-' || t.term_no || '-' ||
        lpad(s.id::text, 6, '0'),
      s.id, t.id, p_due_date, 'unpaid', auth.uid()
    from public.students s
    cross join public.fee_terms t
    where t.id = p_term_id
      and (p_class_id is null or s.class_id = p_class_id)
    on conflict (student_id, term_id) do nothing
    returning id
  ),
  added_items as (
    insert into public.invoice_items (invoice_id, description, amount)
    select id, trim(p_description), p_amount from inserted
    returning id
  )
  select count(*) into created_count from added_items;

  return created_count;
end;
$$;

create or replace function public.refresh_invoice_total()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare target_invoice uuid;
begin
  target_invoice := coalesce(new.invoice_id, old.invoice_id);
  update public.student_invoices
  set total_amount = coalesce((
    select sum(amount) from public.invoice_items where invoice_id = target_invoice
  ), 0),
  updated_at = now()
  where id = target_invoice;
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_refresh_invoice_total on public.invoice_items;
create trigger trg_refresh_invoice_total
after insert or update or delete on public.invoice_items
for each row execute function public.refresh_invoice_total();

create or replace function public.process_payment_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare approved_total numeric(12,2);
begin
  if tg_op = 'INSERT' then
    update public.student_invoices
    set status = 'pending', updated_at = now()
    where id = new.invoice_id and status not in ('paid','cancelled');
  end if;

  if new.status = 'approved' and old.status is distinct from 'approved' then
    new.reviewed_by := coalesce(new.reviewed_by, auth.uid());
    new.reviewed_at := coalesce(new.reviewed_at, now());

    select coalesce(sum(amount), 0) into approved_total
    from public.payments
    where invoice_id = new.invoice_id
      and status = 'approved'
      and id <> new.id;
    approved_total := approved_total + new.amount;

    update public.student_invoices
    set paid_amount = approved_total,
        status = case when approved_total >= total_amount then 'paid' else 'unpaid' end,
        updated_at = now()
    where id = new.invoice_id;

    insert into public.receipts (payment_id, receipt_no, issued_by)
    values (
      new.id,
      'RC' || to_char(current_date, 'YYYYMMDD') || '-' ||
        lpad(nextval('public.receipt_number_seq')::text, 6, '0'),
      new.reviewed_by
    )
    on conflict (payment_id) do nothing;
  elsif tg_op = 'UPDATE' and new.status = 'rejected' then
    update public.student_invoices
    set status = 'unpaid', updated_at = now()
    where id = new.invoice_id and status <> 'paid';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_process_payment_status on public.payments;
create trigger trg_process_payment_status
before insert or update of status on public.payments
for each row execute function public.process_payment_status();

alter table public.fee_terms enable row level security;
alter table public.fee_items enable row level security;
alter table public.student_invoices enable row level security;
alter table public.invoice_items enable row level security;
alter table public.payments enable row level security;
alter table public.receipts enable row level security;

drop policy if exists fee_terms_read on public.fee_terms;
create policy fee_terms_read on public.fee_terms
for select to authenticated using (true);
drop policy if exists fee_terms_staff_all on public.fee_terms;
create policy fee_terms_staff_all on public.fee_terms
for all to authenticated using (public.is_finance_staff())
with check (public.is_finance_staff());

drop policy if exists fee_items_read on public.fee_items;
create policy fee_items_read on public.fee_items
for select to authenticated using (true);
drop policy if exists fee_items_staff_all on public.fee_items;
create policy fee_items_staff_all on public.fee_items
for all to authenticated using (public.is_finance_staff())
with check (public.is_finance_staff());

drop policy if exists invoices_read on public.student_invoices;
create policy invoices_read on public.student_invoices
for select to authenticated using (public.can_access_student(student_id));
drop policy if exists invoices_staff_all on public.student_invoices;
create policy invoices_staff_all on public.student_invoices
for all to authenticated using (public.is_finance_staff())
with check (public.is_finance_staff());

drop policy if exists invoice_items_read on public.invoice_items;
create policy invoice_items_read on public.invoice_items
for select to authenticated using (
  exists (
    select 1 from public.student_invoices i
    where i.id = invoice_id and public.can_access_student(i.student_id)
  )
);
drop policy if exists invoice_items_staff_all on public.invoice_items;
create policy invoice_items_staff_all on public.invoice_items
for all to authenticated using (public.is_finance_staff())
with check (public.is_finance_staff());

drop policy if exists payments_read on public.payments;
create policy payments_read on public.payments
for select to authenticated using (
  public.is_finance_staff()
  or parent_id = auth.uid()
  or exists (
    select 1 from public.student_invoices i
    where i.id = invoice_id and public.can_access_student(i.student_id)
  )
);
drop policy if exists payments_parent_insert on public.payments;
create policy payments_parent_insert on public.payments
for insert to authenticated with check (
  parent_id = auth.uid()
  and status = 'pending'
  and exists (
    select 1
    from public.student_invoices i
    join public.parent_student ps on ps.student_id = i.student_id
    where i.id = invoice_id and ps.parent_id = auth.uid()
  )
);
drop policy if exists payments_staff_update on public.payments;
create policy payments_staff_update on public.payments
for update to authenticated using (public.is_finance_staff())
with check (public.is_finance_staff());

drop policy if exists receipts_read on public.receipts;
create policy receipts_read on public.receipts
for select to authenticated using (
  public.is_finance_staff()
  or exists (
    select 1 from public.payments p
    join public.student_invoices i on i.id = p.invoice_id
    where p.id = payment_id and public.can_access_student(i.student_id)
  )
);

grant select on public.fee_terms, public.fee_items, public.student_invoices,
  public.invoice_items, public.payments, public.receipts to authenticated;
grant insert on public.payments to authenticated;
grant insert, update, delete on public.fee_terms, public.fee_items,
  public.student_invoices, public.invoice_items to authenticated;
grant update on public.payments to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.create_fee_invoices(bigint,text,numeric,date,bigint) to authenticated;

insert into storage.buckets (id, name, public)
values ('payment-slips', 'payment-slips', false)
on conflict (id) do update set public = false;

insert into public.fee_terms (academic_year, term_no, name, is_active)
values ('2569', 1, 'ภาคเรียนที่ 1/2569', true)
on conflict (academic_year, term_no) do update
set name = excluded.name, is_active = true;

drop policy if exists payment_slips_parent_insert on storage.objects;
create policy payment_slips_parent_insert on storage.objects
for insert to authenticated with check (
  bucket_id = 'payment-slips'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists payment_slips_owner_read on storage.objects;
create policy payment_slips_owner_read on storage.objects
for select to authenticated using (
  bucket_id = 'payment-slips'
  and (
    owner_id = auth.uid()::text
    or public.is_finance_staff()
  )
);

-- Example: promote an existing user to finance staff.
-- update public.profiles set role = 'finance'
-- where id = (select id from auth.users where lower(email) = lower('finance@school.example'));
